# Site settings
title: "Corunet | High-quality software and consultancy services"
description: "A software consulting company with an open-source mindset, at Corunet we are experts in all kinds of data-related problems and PCI-compliant systems. We work with startups and Fortune 500s companies, delivering high-quality software."
email: "info@corunet.com"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://corunet.github.io/" # the base hostname & protocol for your site

github_username: corunet

# Build settings
markdown: kramdown

gems:
  - jekyll-inline-svg
svg:
  optimize: true

plugins:
- jekyll-seo-tag

twitter:
  username: corunet
  card: summary

author: "Corunet"
logo: "/img/corunet-logo.png"